### PR TITLE
`Before`, `After` and `Between`

### PR DESCRIPTION
**Pull request by LightAndLight**
Here are some other types that I'm using for relative layouts. I think they could be included in this package.

What do you guys think?

### CODE REVIEW

**Comment by tonymorris** [comment]
:+1:

Needs `Swapped` instances, and Iso' between `Before` and `After`.

**Comment by LightAndLight** [comment]
Roger

**Comment by LightAndLight** [comment]
I think I should write docs for the `Bifoldable` and `Bitraversable` instances too.

**Comment by tonymorris** [comment]
:+1:

**Pull request merged**
